config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs
  
  root to: "users#index"

  resources :users do
    collection do
      get 'search'
    end
  end

  resources :sizes, only: [:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '女性' },
    { id: 2, name: '男性' },

  ]
  include ActiveHash::Associations
  has_many :users
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :user

validates :user,presence:true
end

app/models/staff.rb
class Staff < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :users
        with_options presence:true do
         validates :name
         validates :password
        end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :staff
  has_many :sizes
      extend ActiveHash::Associations::ActiveRecordExtensions
         belongs_to :gender
       
        with_options presence:true do
                validates :first_name,format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "is invalid. Input full-width characters."}
                validates :last_name,format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "is invalid. Input full-width characters."}
                validates :first_name_katakana, format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,message: "全角カタカナのみで入力して下さい"}
                validates :last_name_katakana, format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,message: "全角カタカナのみで入力して下さい"}
                validates :birthday
                validates :address_number,format: { with: /\A\d{3}[-]\d{4}\z/ }
                validates :city
                validates :address
                validates :staff_id,  numericality: { other_than: 0 }
                validates :gender_id,  numericality: { other_than: 0 }
        end
        def self.search(search)
          if search != ""
            User.where('last_name_katakana LIKE(?)', "%#{search}%")
            User.where('first_name_katakana LIKE(?)', "%#{search}%")
            User.where('phone_number LIKE(?)', "%#{search}%")
            User.where('telephone_number LIKE(?)', "%#{search}%")
          else
            User.all
          end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name,:password])
  end
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
  before_action :authenticate_staff!

  def new
    @size = Size.new
  end

  def create
    @size = Size.new(size_params)
    if  @size.save
      redirect_to root_path
    else      
      render :new
    end
  end

  private

  def  size_params 
    params.require(:size).permit(:height, :bust, :hip, :sleeve_length,:user_id,:kimono_yuki,:kimono_height,:kimono_maehaba, :kimono_usirohaba,:kimono_kurikosi,:kimono_katahaba,:kimono_sodehaba,:kimono_sodetuke,:kimono_miyatu,:kimono_okumihaba,:kimono_aiduma,:kimono_sodeguti,:kimono_marumi,:kimono_tumasita,:kimono_erihaba,:kimono_kataaki,:kimono_erikata,:kimono_detail)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_staff!
  before_action :search_product, only: [:index, :search]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if  @user.save
      redirect_to root_path
    else      
      render :new
    end
  end

  def search
    @users = User.search(params[:search])
    @results = @p.result.includes(:staff)
    set_product_column
  end


  private

  def  user_params 
    params.require(:user).permit(:first_name, :last_name, :first_name_katakana, :last_name_katakana,:birthday,:phone_number,:telephone_number,:address_number, :city,:building,:address,:staff,:detail,:gender_id,:staff_id)
  end

  def search_product
    @p = User.ransack(params[:q])
  end

  def set_product_column
    @staff_id = User.select("staff_id").distinct
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gohuku32528</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sizes/new.html.erb
<div class="sizes-contents">
  <div class="sizes-main">
    <h2 class="size-title">寸法入力画面</h2>
    <%= form_with model: @size, url: sizes_path, method: :post, local: true do |f| %>
     <%= render 'users/shared/error_messages', model: f.object %>
        <div class="user-sizes">
         <div class="user-size-title">お客様の基本データ
         </div>
          <div class="personal_id">
           <div class="weight-bold-text">
             顧客ID
            <span class="indispensable">必須</span>
           </div>
            <%= f.text_area :user_id, class:"user_id", id:"user-name",size: "15x1",  placeholder:"顧客ID(顧客データ参照)" %>
          </div>
          <div class="items-explain">
            <div class="weight-bold-text">
              身長
            </div>
            <%= f.text_area :height, class:"user_height", id:"user-height", placeholder:"お客様の身長(高齢の方は変わっている可能性もあるので注意)" %>
          </div>
          <div class="items-explain">
            <div class="weight-bold-text">
              胸囲
            </div>
            <%= f.text_area :bust, class:"user_bust", id:"user-bust",size: "10x1",  placeholder:"お客様の胸囲" %>
          </div>
          <div class="items-explain">
            <div class="weight-bold-text">
              ヒップ
            </div>
            <%= f.text_area :hip, class:"user_hip", id:"user-hip",size: "10x1", placeholder:"お客様のヒップ" %>
          </div>
          <div class="items-explain">
            <div class="weight-bold-text">
              裄
            </div>
            <%= f.text_area :sleeve_length, class:"user_sleeve_length", id:"user-sleeve-length", size: "10x1",placeholder:"お客様の裄" %>
          </div>
        </div>
        <div class="kimono_size">
         <div class="kimono-size">着物寸法
         </div>
          <div class="form">
            <div class="weight-bold-text">
              身丈
            </div>
            <%= f.text_area :kimono_height, class:"kimono_height", id:"kimono_height",size: "10x1", placeholder:"身丈(肩)" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              裄
            </div>
            <%= f.text_area :kimono_yuki, class:"kimono_yuki", id:"kimono_yuki", size: "10x1",placeholder:"裄" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              前巾
            </div>
            <%= f.text_area :kimono_maehaba, class:"kimono_maehaba", id:"kimono_maehaba", size: "10x1",placeholder:"前巾" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              後巾
            </div>
            <%= f.text_area :kimono_usirohaba, class:"kimono_usirohaba", id:"kimono_usirohaba", size: "10x1",placeholder:"繰越" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              繰越
            </div>
            <%= f.text_area :kimono_kurikosi, class:"kimono_kurikosi", id:"kimono_kurikosi", size: "10x1",placeholder:"繰越" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              肩巾
            </div>
            <%= f.text_area :kimono_katahaba, class:"kimono_katahaba", id:"kimono_katahaba",size: "10x1", placeholder:"肩巾" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              袖巾
            </div>
            <%= f.text_area :kimono_sodehaba, class:"kimono_sodehaba", id:"kimono_sodehaba", size: "10x1",placeholder:"袖巾" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              袖付
            </div>
            <%= f.text_area :kimono_sodetuke, class:"kimono_sodetuke", id:"kimono_sodetuke", size: "10x1",placeholder:"袖付" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              袖丸み
            </div>
            <%= f.text_area :kimono_marumi, class:"kimono_marumi", id:"kimono_marumi", size: "10x1",placeholder:"袖丸み" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              褄下
            </div>
            <%= f.text_area :kimono_tumasta, class:"kimono_tumasita", id:"kimono_tumasita", size: "10x1",placeholder:"褄下" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              衿巾
            </div>
            <%= f.text_area :kimono_erihaba, class:"kimono_erihaba", id:"kimono_erihaba",size: "10x1", placeholder:"衿巾" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              肩明
            </div>
            <%= f.text_area :kimono_yuki, class:"kimono_yuki", id:"kimono_yuki",size: "10x1", placeholder:"裄" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              衿肩
            </div>
            <%= f.text_area :kimono_erikata, class:"kimono_erikata", id:"kimono_erikata",size: "10x1", placeholder:"衿肩" %>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              詳細
            </div>
            <%= f.text_area :kimono_yuki, class:"kimono_yuki", id:"kimono_yuki", size: "10x1",placeholder:"詳細(着物の柄や加工する上でのお客様との約束事など必ず記載)" %>
          </div>
        </div>

        <div class="sell-btn-contents">
          <%= f.submit "登録する" ,class:"back-btn" %>
          <%=link_to 'もどる', root_path, class:"back-btn" %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<header class='top-page-header'>
  <%= link_to '顧客管理システム', "/", class:"main_title" %>
</header>
<div class='main'>
  <div class='select-reason-contents'>
    <ul class='reason-lists'>
      <li class='list'>
        <%= link_to '顧客登録',new_user_path, method: :get %>
      </li>
      <li class='list'>
        <%= link_to 'リストアップ検索',search_users_path, method: :get %>    
      </li>
      <li class='list'>
        <%= link_to '寸法入力',new_size_path, method: :get %>
      </li>
    </ul>
    
  </div>
</div>

app/views/users/new.html.erb
<%= form_with model: @user, url: users_path, method: :post, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      顧客情報入力
    </h1>
  </div>
  <%=link_to 'もどる', root_path, class:"back-btn" %>
  <%= render 'users/shared/error_messages', model: f.object%>
  <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">担当</label>
        <span class="indispensable">必須</span>
      </div>
    <%= f.text_field :staff_id, class:"input-default", id:"staff_id",size: "10x1",  placeholder:"例）1"%>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", size: "15x1", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name",size: "15x1",  placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name_katakana, class:"input-name", id:"last-name-kana",size: "15x1",  placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_name_katakana, class:"input-name", id:"first-name-kana", size: "15x1", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class="weight-bold-text">
          性別
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box", id:"gender"}) %>
    </div>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        住所入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :address_number, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県、市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）神奈川県横浜市緑区" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :address, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :building, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">携帯電話番号</label>
          <span class="indispensable">任意</span>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">固定電話番号</label>
          <span class="indispensable">任意</span>
        </div>
        <%= f.text_field :telephone_number, class:"input-default", id:"telephone-number", placeholder:"例）0311111111",maxlength:"11"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">詳細</label>
          <span class="indispensable">任意</span>
        </div>
        <%= f.text_field :detail, class:"input-default", id:"detail", placeholder:"例）職種や好み家族構成など"%>
      </div>
    </div>
  </div>
  <div class='register-btn'>
    <%= f.submit "顧客登録" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

app/views/users/search.html.erb
<div class="search-page" >
  <%= link_to 'トップページに戻る',"/",class:"main_title"%>
  <h1>
    担当別リストアップ検索
  </h1>
  <%= search_form_for @p, url: search_users_path do |f| %>
    <%= f.label :staff_id_eq, '担当名' %>
    <%= f.collection_select :staff_id_eq, @users, :staff_id, :staff_id,  include_blank: '指定なし' %>
    <%= f.submit '検索' %>
  <% end %>


  <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "名前を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>

  <ul class='item-lists'>
    <% @users.each do |user| %>
    <li>
      <%= user.last_name %>
      <%= user.first_name %>
      <%= user.phone_number %>
      <%= user.telephone_number%>
      <%= user.address %>
      <%= user.city %>
      <%= user.address%>
      <%= user.staff[:name] %>
    </li>
    <% end %>
  </ul>
</div>

app/views/users/shared/_error_messages.html.erb
<% if model.errors.any? %>
 <div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
 </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>